# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e9a3493593634322d5f9b8a2ee57218ff3cb787ba4cb1566cbca48637b8c2877871e07f2b0f07d3435af1cc6b904742d41aad5961c9c938f9e1931a05624cf

test:
  secret_key_base: a052c28e17664170a5c92925497c44c2aac6f983b9dc83929d8426b7035bb0c3ca4d13a65b7aa0c90ee1c4237970a79ec043c3339992fcb4c76946eee112de99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
